name: vello_motorista
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (versões mais recentes)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_database: ^12.0.0  # ADICIONAR ESTA LINHA
  url_launcher: ^6.3.0

  # Notificações (substituto do awesome_notifications)
  flutter_local_notifications: ^19.4.0

  # QR Scanner (substituto do qr_code_scanner)
  mobile_scanner: ^7.0.1

  # Mapa (NECESSÁRIO para HomeScreen)
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  font_awesome_flutter: ^10.7.0
  # Audio (NECESSÁRIO para SoundService)
  audioplayers: ^6.1.0

  # Outras dependências atualizadas
  http: ^1.2.2
  shared_preferences: ^2.3.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Remova as linhas abaixo se as pastas não existirem:
    # - assets/documents/
    # - assets/config/