name: vello_motorista
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase (versões mais recentes)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  
  # Notificações (substituto do awesome_notifications)
  flutter_local_notifications: ^17.2.3
  
  # QR Scanner (substituto do qr_code_scanner)
  mobile_scanner: ^5.2.3
  
  # Mapa (NECESSÁRIO para HomeScreen)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Audio (NECESSÁRIO para SoundService)
  audioplayers: ^6.1.0
  
  # Outras dependências atualizadas
  http: ^1.2.2
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    # Remova as linhas abaixo se as pastas não existirem:
    # - assets/documents/
    # - assets/config/

