// File generated by ChatGPT based on google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fVWOzdLDXbxuTO38GRMV4TYCo9-vVR4',
    appId: '1:694167397444:android:4465fc32a5ab1488b6c811',
    messagingSenderId: '694167397444',
    projectId: 'vello-dac50',
    storageBucket: 'vello-dac50.firebasestorage.app',
  );
}
