name: vello_motorista
description: "Aplicativo Vello para Motoristas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (cluster novo, compatível entre si)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_database: ^12.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0

  # Localização
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # Mapas
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  # HTTP
  http: ^1.4.0

  # UI e Navegação
  provider: ^6.1.5
  shared_preferences: ^2.3.3

  # Áudio
  audioplayers: ^6.1.0

  # Utilitários
  intl: ^0.20.1
  image_picker: ^1.0.4
  device_info_plus: ^11.5.0

  # Ícones e fontes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Voz e fala
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0

  # Câmera e sensores
  camera: ^0.11.0+2
  sensors_plus: ^6.0.1

  # Conectividade e Bluetooth
  connectivity_plus: ^6.1.0
  flutter_blue_plus: ^1.32.7

  # Notificações locais
  flutter_local_notifications: ^19.4.1

  # Persistência
  sqflite: ^2.4.1

  # Gráficos
  fl_chart: ^1.0.0

  # Animações
  lottie: ^3.3.0

  # Widgets
  flutter_slidable: ^4.0.1

  # Social
  share_plus: ^11.1.0
  url_launcher: ^6.3.1

  # Calendário
  table_calendar: ^3.1.2

  # QR Code / Scanner
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icons/
    - assets/vello_motorista.png
